export const ERRORS = {
  noInternet: 'No Internet Connection',
  somethingWent: 'Something went wrong, please try again later!',
  enterEmail: 'Please enter a valid email',
  enterPassword: 'Please enter a valid password',
  enterName: 'Please enter name',
  enterNewPassword: 'Please enter a new password',
  enterConfirmPassword: 'Please enter a confirm password',
  enterCurrentPassword: 'Please enter a current password',
  passwordValidation: 'Password must be at least 8 characters long',
  phoneEnter: 'Please enter phone number',
  termsAndCondition: 'Please accept the terms and conditions',
  emptyForm: 'Fields should not be empty',
  nameLength: 'Name should not be less than 3 characters',
  phoneValidation: 'phone number is not valid',
  email: 'Please enter email address',
  enterFullName: 'Please enter full name',
  enterDateOfBirth: 'Please enter date of birth',
  selectDegree: 'Please select degree',
  selectOccupation: 'Please select occupation',
  enterEmployer: 'Please enter employer',
  selectIncome: 'Please select income',
  selectWorkLocation: 'Please select work location',
  employerLength: 'Company name should not be less than 5 characters',
};
