import { AccountSettingsScreen } from "../screens";

export const LABELS = {
  cancel:'Cancel',
  newPass: 'New Password',
  chnagePassMsg: 'Reset your password for account access.',
  changePass: 'Change Password',
  maritalExpectation: 'Marital Expectation',
  highestEducation: 'Highest Education',
  employedIn: 'Employed In',
  partnerExpectation: 'Partner Expectation',
  educationCareer: 'Education Career',
  presentAddress: 'Present Address',
  PreminentAddress: 'Preminent Address',
  locationInfo: 'Location Information',
  exampleEmail: 'Person@email.com',
  email: 'Email',
  contactDetails: 'Contact Details',
  disability: 'Disability',
  cast: 'Cast',
  profileCreatedFor: 'Profile Created For',
  new: 'New',
  createAccount: 'Create an account',
  login: 'Log in',
  initialMessage: 'Find your perfect match on this ',
  continueInitialMsg: 'matrimony app',
  register: 'Get Register',
  registerMsg: 'Please get register to continue.',
  fullName: 'Full Name',
  johnSmith: 'John Smith',
  emailPlaceholder: 'John_Smith@email.com',
  emailAddress: 'Email Address',
  phoneNumber: 'Phone Number',
  phonePlaceholder: '3456999 9',
  Password: 'Password',
  passwordPlaceholder: '******',
  checkboxLabel: 'I agree to the Terms of use And Privacy Policy',
  welcomeBack: 'Welcome Back!',
  loginMessage: 'Please Log in to continue.',
  rememberMe: 'Remember me!',
  forgotPass: 'Forgot Password?',
  continueWith: 'Or continue with',
  alreadyHaveAccount: 'Already have an account?  ',
  signIn: 'Sign in',
  enterVeification: 'Enter Verification Code',
  verificationMsg: 'Enter code that we have sent to your email',
  resendCode: 'Resend Code',
  profileCreation: 'Profile Creation',
  profileCreateMsg: 'Please provide the following information',
  Male: 'Male',
  Gender: 'Gender',
  continue: 'Continue',
  highestDegree: 'Highest Degree',
  occupation: 'Occupation',
  employIn: 'Employ in',
  AnnualIncome: 'Annual Income',
  workLocation: 'Work Location',
  select: 'Select',
  employePlaceholder: 'AX Technlogy',
  incomePlaceholder: '12 Lac',
  workLocationPlaceholder: 'Mumbai',
  partnerPreference: 'Partner Preference',
  dateOfBirth: 'Date of Birth',
  birthdayPlaceholder: '(dd/mm/yyy)',
  match: 'I Would like to match with',
  age: 'Age',
  maritalStatus: 'Marital Status',
  contentPartnerPreference:
    'Provide more details on thr people you want to match, base on your preference',
  addMore: 'Add more speciality ',
  height: 'Height',
  education: 'Education',
  motherToungue: 'Mother Tongue',
  sect: 'Sect',
  city: 'City',
  save: 'Save',
  searchHere: 'Search here...',
  NewJoin: 'New Join',
  matches: 'Matches',
  nearestMe: 'Nearest me',
  recentlyViewed: 'Recently Viewed',
  seeMore: 'See More',
  sendInterest: 'Send Interest',
  chat: 'Chat',
  mumbaiIndia: 'Mumbai, India',
  exampleLanguage: 'Hindi, Bengali',
  castName: 'Cast Name',
  exampleName: 'Michel Clark',
  businessMan: 'Business Man',
  preference: 'Engineer Preference',
  selectEducation: 'Select Education',
  ShusmitaSharma: 'Shusmita Sharma',
  AssistantManager: 'Assistant Manager',
  examplePara:
    'Lorem ipsum dolor sit amet,adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  basicInfo: 'Basic Information',
  name: 'Name',
  neverMarried: 'Never Married',
  inbox: 'Inbox',
  notification: 'Notifications',
  profile: 'Profile',
  connection: 'Connections',
  AccountSettingsScreen: 'Account Settings',
  accept: 'Accept',
  reject: 'Reject',
  update: 'Update',
  saved: 'Saved',
  selectMembershipPlan: 'Select Plan To Continue',
  goWithThis: 'Go with this',
  membership: 'Subscription Plan',
  Payment: 'Payment',
  uSelected: 'You Selected',
  choosePayMethod: 'Pay with Razor pay',
  cardNumber: 'Card Number',
  cardPlaceholder: 'CardHolder Name',
  saveCreditInfo: 'Save credit card information',
  confirm: 'Confirm',
  back: 'Back',
  signUp: 'Sign Up',
};