import {StyleSheet} from 'react-native';
import {COLORS, HORIZON_MARGIN} from '../../../assets/theme';
export const styles = StyleSheet.create({
  main:{
    backgroundColor:'white',
    paddingHorizontal: 10,
  },
  characterImg: {
    height: 120,
    width: '90%',
    alignSelf: 'flex-start',
  },
  textContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '80%',
    flexDirection: 'row',
  },
  bullet: {
    height: 8,
    width: 8,
    borderRadius: 4,
    backgroundColor: COLORS.dark.primary,
  },
  contentContainer: {
    width: '60%',
    position: 'absolute',
    top: 10,
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginLeft: 15,
    justifyContent: 'center',
    height: 200,
    zIndex: 3,
  },
  selectBtn: {
    height: 35,
    width: '60%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    backgroundColor: COLORS.dark.primary,
  },
  selectedBtn: {
    backgroundColor: COLORS.dark.green,
  },
  characterContainer: {
    justifyContent: 'center',
    height: 200,
    width: '45%',
    alignItems: 'center',
    alignSelf: 'flex-end',
    position: 'absolute',
    zIndex: 2,
  },
  headerContainer: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark.lightGrey,
  },
  cardContainer: {
    height: 210,
    paddingHorizontal: HORIZON_MARGIN,
    justifyContent: 'center',
    width: '100%',
  },
  img: {
    width: '100%',
    height: 200,
    flexDirection: 'row',
    borderRadius: 10,
    marginTop: 20,
    zIndex: 1,
  },
  optionContainer: {
    height: 50,
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.dark.lightGrey,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    justifyContent: 'space-between',
    borderRadius: 5,
  },
  planContainer: {
    width: '90%',
    padding: 20,
    borderRadius: 15,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    marginVertical: 15,
    alignSelf: 'center',
    marginBottom: 10,
    elevation: 5,
  },
  planName: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  featureContainer: {
    flexDirection: 'colomn',
    alignItems: 'left',
    paddingTop: 10,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  feature: {
    fontSize: 16,
    color: '#333',
    marginLeft: 15,
  },
  price: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 20,
    color: '#333',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#ff7f50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});