import {StyleSheet} from 'react-native';
import {COLORS, HORIZON_MARGIN} from '../../../assets/theme';
import {Fonts} from '../../../assets/fonts';
export const styles = StyleSheet.create({
  headerContainer: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark.lightGrey,
  },
  verifyIconContainer: {
    height: 25,
    width: 25,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: COLORS.dark.lightGrey,
  },
  professionLabel: {
    position: 'absolute',
    bottom: 10,
    zIndex: 2,
    fontFamily: Fonts.PoppinsRegular,
  },
  acceptBtn: {
    height: 38,
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.secondary,
  },
  requestBtn: {
    height: 38,
    width: '70%',
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.secondary,
  },
  rejectButton: {
    height: 38,
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.primary,
  },
  chatButton: {
    height: 40,
    width: 40,

    justifyContent: 'center',
    alignItems: 'center',
  },
  acceptBtnContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  requestBtnContainer: {
    width: '100%',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
  },
  btnShownContainer: isBtnShown => ({
    flexDirection: isBtnShown ? 'row' : 'column',
    justifyContent: 'space-between',
    width: '100%',
  }),
  headerContainer: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark.lightGrey,
  },
  searchBoxContainer: {
    width: '100%',
    paddingHorizontal: HORIZON_MARGIN,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  searchBox: {
    height: 50,
    width: '75%',
    backgroundColor: COLORS.dark.lightGrey,
  },
  filterBtn: {
    height: 50,
    width: '15%',
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContainer: {
    height: 125,
    width: '100%',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: COLORS.dark.text,
    flexDirection: 'row',
    borderRadius: 10,
    elevation: 5,
    marginTop: 10,
  },
  imgContainer: {
    width: '35%',
    borderRadius: 20,
  },

  contentContainer: {
    justifyContent: 'center',
    width: '65%',
    maxWidth: '65%',
    paddingHorizontal: HORIZON_MARGIN,
  },
  gradientOverlay: {
    zIndex: 1,
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
  },
  textContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  horizontalScrollContainer: {
    width: '100%',
    height: 150,
  },
  img: {
    flex: 1,
    borderRadius: 10,
  },
  sendIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.primary,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifyIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.dark.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnContainer: {
    flexDirection: 'row',
  },
  sendInterestBtn: {
    width: '70%',
    height: 40,
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 5,
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatBtn: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.dark.primary,
    borderRadius: 5,
  },
  Bell_Icon: {
    width: 25,
    height: 30,
    resizeMode: 'contain',
    marginRight: '1%',
  },
  main: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  cardContainer: {
    width: '48%', // Reduce this value to make sure two cards fit in one row
    height: 190,
    backgroundColor: COLORS.dark.white,
    borderRadius: 15,
    elevation: 5,
    marginBottom: 15,
    overflow: 'hidden',
  },
  imageContainer: {
    height: '60%',
    width: '100%',
    position: 'relative',
  },
  profileImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  newTag: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: COLORS.dark.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  newText: {
    color: COLORS.dark.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  verifiedIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  infoContainer: {
    paddingHorizontal: 5,
    paddingTop: 10,
    marginRight: 10,
  },
  nameLocationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 16,
    alignItems: 'center',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  locationText: {
    fontSize: 10,
    marginLeft: 2,
  },
  detailsText: {
    flex: 1,
    color: COLORS.dark.black,
    marginRight: 10,
  },
  actionContainer: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  occupationText: {
    marginLeft: -10,
    marginBottom: -17,
    width: '70%',
    paddingLeft: 10,
  },
  actionButton1: {
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: '#1E285F14',
    justifyContent: 'center',
    marginLeft: 10,
  },
  actionButton2: {
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: '#F97B221A',
    justifyContent: 'center',
    marginLeft: 10,
  },
  ageHeightActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  test: {
    color: 'black',
    fontSize: 12,
    width:'70%'
  },
  icon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    backgroundColor: 'red',
    marginRight: 5,
  },
  Bell_Icon: {
    width: 25,
    height: 30,
    resizeMode: 'contain',
    marginRight: '1%',
  },
});
