import {StyleSheet} from 'react-native';
import {COLORS, HORIZON_MARGIN} from '../../../assets/theme';
import { Fonts } from '../../../assets/fonts';
export const styles = StyleSheet.create({
  headerContainer: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark.lightGrey,
  },
  mapContainer: {
    height: 55,
    width: '100%',
    backgroundColor: COLORS.dark.lightblue,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  itemsContainer: {
    height: 100,
    width: '100%',
    backgroundColor: 'pink',
  },
  withoutCameraContainer: {
    height: 0,
    backgroundColor: 'red',
    flexDirection: 'row',
    paddingHorizontal: HORIZON_MARGIN,
  },
  selectedBtn: {
    backgroundColor: COLORS.dark.primary,
    borderRadius: 5,
    height: 45,
    width: '33%',
  },
  unSelectedBtn: {
    backgroundColor: COLORS.dark.lightblue,
    width: '33%',
    borderRadius: 0,
  },
  selectedText: {
    color: 'white',
    fontSize: 14,
  },
  unSelectedText: {
    color: 'black',
    fontSize: 14,
  },
  verifyIconContainer: {
    height: 25,
    width: 25,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: COLORS.dark.lightGrey,
  },
  professionLabel: {
    position: 'absolute',
    bottom: 10,
    zIndex: 2,
    fontFamily: Fonts.PoppinsRegular,
  },
  acceptBtn: {
    height: 38,
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.secondary,
  },
  requestBtn: {
    height: 38,
    width: '70%',
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.secondary,
  },
  rejectButton: {
    height: 38,
    marginHorizontal: '10%',
    backgroundColor: COLORS.dark.primary,
  },
  chatButton: {
    height: 40,
    width: 40,

    justifyContent: 'center',
    alignItems: 'center',
  },
  acceptBtnContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  requestBtnContainer: {
    width: '100%',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
  },
  btnShownContainer: isBtnShown => ({
    flexDirection: isBtnShown ? 'row' : 'column',
    justifyContent: 'space-between',
    width: '100%',
  }),
  headerContainer: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark.lightGrey,
  },
  searchBoxContainer: {
    width: '100%',
    paddingHorizontal: HORIZON_MARGIN,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  searchBox: {
    height: 50,
    width: '75%',
    backgroundColor: COLORS.dark.lightGrey,
  },
  filterBtn: {
    height: 50,
    width: '15%',
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContainer: {
    height: 125,
    width: '100%',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: COLORS.dark.text,
    flexDirection: 'row',
    borderRadius: 10,
    elevation: 5,
    marginTop: 10,
  },
  imgContainer: {
    width: '35%',
    borderRadius: 20,
  },

  contentContainer: {
    justifyContent: 'center',
    width: '65%',
    maxWidth: '65%',
    paddingHorizontal: HORIZON_MARGIN,
  },
  gradientOverlay: {
    zIndex: 1,
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
  },
  textContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  horizontalScrollContainer: {
    width: '100%',
    height: 150,
  },
  img: {
    flex: 1,
    borderRadius: 10,
  },
  sendIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.primary,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifyIconBtn: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.dark.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.dark.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnContainer: {
    flexDirection: 'row',
  },
  sendInterestBtn: {
    width: '70%',
    height: 40,
    backgroundColor: COLORS.dark.secondary,
    borderRadius: 5,
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatBtn: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.dark.primary,
    borderRadius: 5,
  },
});
